### ISSUE TITLE
Tensorflow Dependency Error

### ISSUE THREAD

**Issue by lodenrogue** [Christopher-Thornton/hmni#1]
During pip install I'm getting the following error:

ERROR: Could not find a version that satisfies the requirement tensorflow<2.0,>=1.11 (from hmni) (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0)
ERROR: No matching distribution found for tensorflow<2.0,>=1.11 (from hmni)

---------------------------------------------------------------------------------------------------------------
OS details:

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

**Comment by Christopher-Thornton** [comment]
Which version of Python are you using? Please see TensorFlow's [system requirements](https://www.tensorflow.org/install/pip).

**Comment by lodenrogue** [comment]
Which version of tensorflow do you require?

I'm using python 3.8.2

**Comment by Christopher-Thornton** [comment]
HMNI requires TensorFlow 1.x to serve models, some important functions have become deprecated as of TF 2.x and later.

**Comment by lodenrogue** [comment]
Oh, it seems pip installs tensorflow 2.x by default and doesn't offer 1.x anymore (?)

 $ python3 -m pip install tensorflow==
ERROR: Could not find a version that satisfies the requirement tensorflow== (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0)
ERROR: No matching distribution found for tensorflow==

**Comment by Christopher-Thornton** [comment]
Related issue: [Unable to install older version of tensorflow in  #Python3.8.2](https://github.com/tensorflow/tensorflow/issues/39621)
I will be adding support for TensorFlow 2.0+ in future releases.

**Comment by Christopher-Thornton** [comment]
Resolved as of v0.1.6: Alpha Release
- Added TensorFlow 2 compatibility
