### ISSUE TITLE
pandas fuzzy merge with particular distance algorithm

### ISSUE THREAD

**Issue by abubelinha** [Christopher-Thornton/hmni#11]
I see in [requirements](https://github.com/Christopher-Thornton/hmni#python-3538) that hmni uses [abydos](https://github.com/chrislit/abydos) , which in turn is the only package I have found implementing some distance algorithms, like [Rees-Levenshtein](https://abydos.readthedocs.io/en/latest/abydos.distance.html#abydos.distance.ReesLevenshtein).

I wonder if someone could provide an example of how to fuzzy merge two pandas dataframes on a common column, but stablishing a minimal distance cutoff using that particular algorithm.

```Python
import pandas as pd
df1 = pd.DataFrame({"name":["Johnn Doe", "Jon Doe", "Margaret Tacher", "Marareth Tatcher"]})
df2 = pd.DataFrame(
	[["John Doe", "US"],["Margareth Thatcher","UK"]],
	columns=["name", "country"])
```
For example, get country for each person name in df1, based on fuzzy matches against df2 with a particular algorithm.

Is it possible to do that with hmni?
I should use `fuzzymerge` method, but I can't figure out how to specify an algorithm taken from abydos.

Thanks a lot for your help in advance

**Comment by Christopher-Thornton** [comment]
@abubelinha You would need to modify the source code in my package, specifically the [similarity function](https://github.com/Christopher-Thornton/hmni/blob/master/hmni/matcher.py#L166-L275).

Currently a number of string distance measures implemented in the abydos library are computed as features for model inference.
