### ISSUE TITLE
Code from your tutorial

### ISSUE THREAD

**Issue by OleksiyAnokhin** [Christopher-Thornton/hmni#13]
@Christopher-Thornton , thanks for a great library!
Did you share the code, which you used for building a model?
https://towardsdatascience.com/fuzzy-name-matching-with-machine-learning-f09895dce7b4
I am looking to match 30000+ vs 5000+ names and I am trying to find a solution, which would be tailored for names specifically. 
This is exactly what I need
![image](https://user-images.githubusercontent.com/24446791/171386621-49217fe1-04c4-4482-93f7-ca009b72a680.png)

**Comment by Christopher-Thornton** [comment]
All the relevant code for training a new model can be found in [model_building.ipynb](https://github.com/Christopher-Thornton/hmni/blob/master/dev/model_building.ipynb).
