### ISSUE TITLE
ModuleNotFoundError: No module named 'syllable_tokenizer'

### ISSUE THREAD

**Issue by OleksiyAnokhin** [Christopher-Thornton/hmni#14]
Hi @Christopher-Thornton 

What should I install to resolve this? Did not find any answer. Thanks!

     ModuleNotFoundError: No module named 'syllable_tokenizer'

**Comment by Christopher-Thornton** [comment]
This is a module in my package you can import: [hmni/syllable_tokenizer.py](https://github.com/Christopher-Thornton/hmni/blob/9c6fa948707c233c24d11bb43bb67e818e0cfd1c/hmni/syllable_tokenizer.py)
