### ISSUE TITLE
UserWarning: Trying to unpickle estimator MinMaxScaler from version 0.23.1 when using version 1.0.2. 

### ISSUE THREAD

**Issue by OleksiyAnokhin** [Christopher-Thornton/hmni#16]
Hello again :)
I am trying to use the library and get this error

`UserWarning: Trying to unpickle estimator MinMaxScaler from version 0.23.1 when using version 1.0.2. `

Downgradit scikit did not help. How do you resolve situations like this? Thanks!

**Comment by OleksiyAnokhin** [comment]
@Christopher-Thornton , still interested, cannot resolve conflicts

**Comment by Christopher-Thornton** [comment]
If there are dependency issues that arise from this two year old project, don't expect me to maintain and immediately patch.
I have newer projects I am personally invested in; this one isn't dead but a lower priority to receive updates.

**Comment by OleksiyAnokhin** [comment]
Okay, no worries, just wanted to raise it. Thanks for a great project.
