### ISSUE TITLE
licence compatibility

### ISSUE THREAD

**Issue by alaniwi** [Christopher-Thornton/hmni#2]
I believe that you can incorporate third-party code under an MIT licence in a package released under Apache 2.0 licence but _not the other way round_ -- see e.g. https://dwheeler.com/essays/floss-license-slide.html .

As the third-party code used here is under a mixture of these two licences -- in particular the [code from nltk](https://github.com/nltk/nltk/blob/develop/nltk/tokenize/sonority_sequencing.py) (here `hmni/syllable_tokenizer.py`) is [under Apache 2.0](https://github.com/nltk/nltk/blob/develop/LICENSE.txt) -- the whole thing needs to be under Apache 2.0 (or compatible) rather than MIT.

**Comment by Christopher-Thornton** [comment]
Thanks for bringing this to my attention. Given that I have dependencies from multiple licences (MIT, Apache 2.0, GPLv2+, BSD),  I will have to make sure my licence is compatible. Any suggestions on that end?

**Comment by Christopher-Thornton** [comment]
Thanks for bringing this to my attention.  I will be minimizing third-party dependencies in future releases and hope to maintain the MIT licence if possible.

**Comment by Christopher-Thornton** [comment]
Resolved as of v0.1.5: Alpha Release
