### ISSUE TITLE
fuzzymerge throws float indexing error

### ISSUE THREAD

**Issue by gloriamacia** [Christopher-Thornton/hmni#7]
![image](https://user-images.githubusercontent.com/17580456/110358383-a1731900-803c-11eb-8f03-89fdefb3c24b.png)

**Comment by Christopher-Thornton** [comment]
@gloriamacia Thanks for bringing this issue to my attention, I need to do more testing and debugging of the `fuzzymerge` method so it always works as intended.

Update: I made a small change to fix the TypeError, but haven't done full test coverage of the method.
