### ISSUE TITLE
featurize(df) throwing error: AttributeError: module hmni.syllable_tokenizer has no attribute 'tokenize'

### ISSUE THREAD

**Issue by farinexile** [Christopher-Thornton/hmni#9]
Hi!
I was trying to implement hmni model with source code. Python 3.8.5, pandas 1.1.3, sklearn 0.23.2

I am facing the following error when running featurize(df) in model_building.ipynb:

AttributeError: module hmni.syllable_tokenizer has no attribute 'tokenize'

from the following code:
df['syll_a']= df.apply(lambda row: syllable_tokenizer.tokenize(row.name_a), axis=1)

How can we solve this?

Thanks,
Farhana

**Comment by Christopher-Thornton** [comment]
The function name in [syllable_tokenizer.py](https://github.com/Christopher-Thornton/hmni/blob/9c6fa948707c233c24d11bb43bb67e818e0cfd1c/hmni/syllable_tokenizer.py) was changed from `tokenize` to `syllables` 

To fix the error replace the line with:
`df['syll_a']= df.apply(lambda row: syllable_tokenizer.syllables(row.name_a), axis=1)`

**Comment by farinexile** [comment]
Thank you for your response Chris, I tried it out later and it worked. 

Best,
Farhana
